=== kentuck-tech-inc/build360/definitions/individualBuilder.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "builderUUID": {
      "type": "string"
    },
    "builderCompanyName": {
      "type": "string"
    },
    "builderOwner": {
      "type": "string"
    },
    "associations": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "yearEstablished": {
      "type": "integer"
    },
    "builderDescription": {
      "type": "string"
    },
    "bbbRating": {
      "type": "string"
    },
    "builderPortfolio": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "builderContactInfo": {
      "type": "object",
      "properties": {
        "addressStreet1": {
          "type": "string"
        },
        "adressStreet2": {
          "type": "string"
        },
        "addressCity": {
          "type": "string"
        },
        "addressState": {
          "type": "string"
        },
        "addressZip": {
          "type": "integer"
        },
        "primaryPhone": {
          "type": "string"
        },
        "primaryEmail": {
          "type": "string"
        },
        "socialMedia": {
          "type": "object",
          "properties": {
            "twitter": {
              "type": "string"
            },
            "facebook": {
              "type": "string"
            }
          },
          "required": [
            "twitter",
            "facebook"
          ]
        }
      },
      "required": [
        "addressStreet1",
        "adressStreet2",
        "addressCity",
        "addressState",
        "addressZip",
        "primaryPhone",
        "primaryEmail",
        "socialMedia"
      ]
    },
    "builderFeedback": {
      "type": "object",
      "properties": {
        "communication": {
          "type": "number"
        },
        "professionalism": {
          "type": "number"
        },
        "job site cleanliness": {
          "type": "number"
        },
        "budget mindful": {
          "type": "number"
        },
        "quality of materials": {
          "type": "number"
        },
        "deadlines": {
          "type": "number"
        },
        "quality of worksmanship": {
          "type": "number"
        },
        "finished product": {
          "type": "number"
        },
        "accuracy of quote and allowances": {
          "type": "number"
        },
        "overall": {
          "type": "number"
        }
      },
      "required": [
        "communication",
        "professionalism",
        "job site cleanliness",
        "budget mindful",
        "quality of materials",
        "deadlines",
        "quality of worksmanship",
        "finished product",
        "accuracy of quote and allowances",
        "overall"
      ]
    }
  },
  "required": [
    "builderUUID",
    "builderCompanyName",
    "builderOwner",
    "associations",
    "yearEstablished",
    "builderDescription",
    "bbbRating",
    "builderPortfolio",
    "builderContactInfo",
    "builderFeedback"
  ]
}

=== kentuck-tech-inc/build360/definitions/individualBuilder.json
{
  "builderUUID" : "???",
 "builderCompanyName": "Doe Construction",
 "builderOwner": "john doe",
  "associations": ["LTHBA", "NHBA"],
  "yearEstablished": 1999,
  "builderDescription" : "Hi, my name is Bob Builder, Central Kentuck's most elite...",
  "bbbRating":"A",
  "builderPortfolio" : [
    {"blueprint_id":"blueprintUUID1",
      "orderId": 1},
    {"blueprint_id":"blueprintUUID2",
      "orderId": 2}],
 "builderContactInfo" : 
  {
   "addressStreet1" : "1234 High Rise Avenue",
   "adressStreet2" : "",
   "addressCity" : "Elizabethtown",
   "addressState" : "Kentucky",
   "addressZip" : 42701,
   "primaryPhone" : "270-777-7777",
   "primaryEmail" : "test@test.com",
   "socialMedia" : 
   {
    "twitter" : "bobBuilderLLC",
    "facebook" : "facebook.com/bobBuilderLLC"
   }
  },
  "builderFeedback" : 
  {
   "communication" : 1.0,
    "professionalism" : 0.99,
    "job site cleanliness" : 0.8,
    "budget mindful" : 0.7,
    "quality of materials" : 0.01,
    "deadlines": 0.98,
    "quality of worksmanship" : 0.50,
    "finished product" : 1.0,
    "accuracy of quote and allowances" : 1.0,
    "overall" : 0.98
  }
}
